doc-valid-idents = [
	"..", # Include the built-in valid idents list
	"AArch32",
	"AArch64",
	"ANDing",
	"ARMv8",
	"CONST_CASE",
	"CS140e",
	"DTSpec",
	"DeviceTree",
	"InterProcessor",
	"ORing",
	"TitleCase",
	"X86_64",
	"XMMn",
	"YMMn",
	"ZMMn",
	"snake_case",
	"x86_64",
]
absolute-paths-allowed-crates = [
	"core",
	"std",
	"alloc",
	"compiler_builtins",
]
