doc-valid-idents = [
	"..", # Include the built-in valid idents list
	"AArch64",
	"ANDing",
	"ARMv8",
	"CONST_CASE",
	"CS140e",
	"DTSpec",
	"DeviceTree",
	"InterProcessor",
	"ORing",
	"TitleCase",
	"X86_64",
	"XMMn",
	"YMMn",
	"ZMMn",
	"snake_case",
	"x86_64",
]
