[toolchain]
channel = "nightly-2024-10-19"
components = [ "rustfmt", "rustc-dev", "clippy", "rust-src", "llvm-tools-preview" ]
targets = [ "x86_64-unknown-none", "aarch64-unknown-none" ]
profile = "minimal"
