[toolchain]
channel = "nightly-2026-01-20"
components = [
	"clippy",
	"llvm-tools-preview",
	"rust-src",
	"rustc-dev",
	"rustfmt",
]
targets = [
	"aarch64-unknown-none",
	"x86_64-unknown-none",
]
profile = "minimal"
