[toolchain]
# Upgrade pending on https://github.com/rust-lang/cargo/issues/7614#issuecomment-3573261644
channel = "nightly-2025-11-05"
components = [
	"clippy",
	"llvm-tools-preview",
	"rust-src",
	"rustc-dev",
	"rustfmt",
]
targets = [
	"aarch64-unknown-none",
	"x86_64-unknown-none",
]
profile = "minimal"
